### PR TITLE
Add `wext-manifest`

### PR DESCRIPTION
**Pull request by abhijithvijayan**
Generated manifest.json for edge/firefox/chrome/safari from a single js file with options specific to browsers

### CODE REVIEW

**Comment by fregante** [comment]
This is interesting, but when does one actually need to customize `manifest.json` "per browser"?

Chrome might complain about some properties and Firefox about others, but in the end they coexist. None of the examples in the readme break anything if `__browser__` was not there.

**Comment by abhijithvijayan** [comment]
Warning could be easily avoided and also I have run into situations like copying contents on clipboard which in chrome doesnt require `clipboardWrite` to do that but firefox requires it.

I think its better to generate browser tailored manifest files so as not to bloat the contents.

**Comment by fregante** [comment]
I still think "manifest bloat" isn't an issue, but the tool is valid, so I'll accept it :)

Can you move it to the Tools section?

**Comment by abhijithvijayan** [comment]
Done.

Thanks as well.

**Pull request merged**
